{{ define "mysqlHook" }}
recreateParams:
  post:
    execNewPod:
      command:
        - /bin/sh
        - '-c'
        - >-
          curl -o ~/schema-mysql.sql 
          {{ .Values.schemaUrl }}
          && /usr/bin/mysql -h mysql --protocol TCP -u
          $MYSQL_USER -D $MYSQL_DATABASE -p$MYSQL_PASSWORD <
          ~/schema-mysql.sql
      containerName: mysql
    failurePolicy: abort
{{ end }}