apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-sizing
spec:
  host: kafka-sizing-openshift-gitops.apps.ocpvirt.localdomain
  port:
    targetPort: {{ .Values.port }} 
  to:
    kind: Service
    name: {{ .Values.appName }}
  port:
    targetPort: kafka-sizing
