apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    name: kafka-sizing
  selector:
    app: {{ .Values.appName }}
    tier: frontend
