kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  spring.datasource.password: {{ .Values.databaseRootPassword }}
  app.default.vcpuIncrement: '2'
  logging.level.com.appsdeveloperblog.examples: INFO
  spring.session.jdbc.table-name: SPRING_SESSION
  spring.datasource.url: 'jdbc:mysql://mysql:3306/springSession'
  spring.datasource.initialization-mode: never
  app.default.vcpusPerZkNode: '4'
  spring.profiles.active: '@activatedProfile@'
  spring.application.name: kafka-sizing
  app.default.vcpusPerBroker: '8'
  app.default.memPerZkNode: '16'
  server.servlet.session.timeout: 30m
  app.default.diskPerZkNode: '100'
  app.default.memPerBroker: '32'
  spring.datasource.platform: mysql
  app.default.safetyFactor: '1.6'
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.datasource.username: root
  spring.session.store-type: 'jdbc '
