appName: kafka-sizing

port: 8080

replicas: 1

configmap:
  name: kafka-sizing

databaseRootPassword: sa

image:
  name: quay.io/andyyuen/kafka-sizing-mysql
  tag: latest

requests:
  memory: 200Mi
  cpu: 100m

limits:
  memory: 500Mi
  cpu: 400m
